[package]
version = "0.1.0"
name = "tx_transfer"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
ethers = "2.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
toml = "0.7"
anyhow = "1.0.93"
